inherit_from: .rubocop_todo.yml
require: rubocop-rails

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

