version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      TZ: Asia/Tokyo
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  web:
    stdin_open: true
    tty: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/tich-api
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_HOST=db
