name: "Ruby on Rails CI"
on:
  - push
  - pull_request
env:
  RAILS_ENV: test
  DATABASE_HOST: 127.0.0.1
  REDIS_URL: redis://127.0.0.1:6379/1
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          TZ: Asia/Tokyo
        ports:
          - 5432:5432
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          bundler-cache: true
      - name: Set up database schema
        run: bundle exec rails db:create db:schema:load
      - name: Run Rspec
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          ruby-version: '2.7.6'
          bundler-cache: true
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
        
